name 'mcelog'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures mcelog to catch and decode hardware errors from the Linux kernel'
version           '2.2.4'
source_url        'https://github.com/sous-chefs/mcelog'
issues_url        'https://github.com/sous-chefs/mcelog/issues'
chef_version      '>= 15.3'

supports 'debian'
supports 'ubuntu'
supports 'redhat'
supports 'centos'
supports 'oracle'
supports 'scientific'
supports 'almalinux'
supports 'rocky'
