---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@6.0.0
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    uses: sous-chefs/.github/.github/workflows/integration.yml@6.0.0
    with:
      os:
        - almalinux-8
        - almalinux-9
        - debian-11
        - debian-12
        - oraclelinux-8
        - oraclelinux-9
        - rockylinux-8
        - rockylinux-9
        - ubuntu-20.04
        - ubuntu-22.04
        - ubuntu-24.04
      suite:
        - default
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write
